[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps --include=dev && npm run build:backend"

[deploy]
startCommand = "npm run start:backend"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
NODE_OPTIONS = "--experimental-global-webcrypto"